services:
  database:
    image: 'postgres:latest'
    container_name: postgres_db
    environment:
      - 'POSTGRES_DB=userhub_db'
      - 'POSTGRES_USER=userhub'
      - 'POSTGRES_PASSWORD=secret'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    container_name: spring_app
    depends_on:
      - database
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/userhub_db'
      - 'SPRING_DATASOURCE_USERNAME=userhub'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=none'
      - 'SPRING_FLYWAY_ENABLED=true'

  frontend:
    build: ./frontend
    container_name: angular_app
    ports:
      - '4200:80' 
    depends_on:
      - backend

volumes:
  postgres_data: